create database bd_identidades;
create database bd_marketplace;
create database bd_logistica;
create database bd_inventario;
create database bd_pagos;
create database bd_ordenes;
create database bd_resenas;
create database bd_logistica;
create database bd_carrito;