spring.application.name=api-gateway
server.port=8090
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.instance.prefer-ip-address=true

# Nexo entre identidad-service y API Gateway.

spring.cloud.gateway.server.webflux.routes[0].id=identidad
spring.cloud.gateway.server.webflux.routes[0].uri=lb://identidad-service
spring.cloud.gateway.server.webflux.routes[0].predicates[0]=Path=/usuarios/**, /roles/**

# Nexo entre marketplace-service y API Gateway

spring.cloud.gateway.server.webflux.routes[1].id=marketplace
spring.cloud.gateway.server.webflux.routes[1].uri=lb://marketplace-service
spring.cloud.gateway.server.webflux.routes[1].predicates[0]=Path=/vendedores/**

spring.main.web-application-type=reactive;
server.address=0.0.0.0