spring.application.name=api-gateway
server.port=8090
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.instance.prefer-ip-address=true

# Nexo entre identidad-service y API Gateway.

spring.cloud.gateway.server.webflux.routes[0].id=identidad
spring.cloud.gateway.server.webflux.routes[0].uri=lb://identidad-service
spring.cloud.gateway.server.webflux.routes[0].predicates[0]=Path=/usuarios/**, /roles/**

# Nexo entre marketplace-service y API Gateway

spring.cloud.gateway.server.webflux.routes[1].id=marketplace
spring.cloud.gateway.server.webflux.routes[1].uri=lb://marketplace-service
spring.cloud.gateway.server.webflux.routes[1].predicates[0]=Path=/vendedores/**, /productos/**, /tiendas/**, /categorias/**
spring.main.web-application-type=reactive;
server.address=0.0.0.0

spring.cloud.gateway.server.webflux.routes[2].id=inventario
spring.cloud.gateway.server.webflux.routes[2].uri=lb://inventario-service
spring.cloud.gateway.server.webflux.routes[2].predicates[0]=Path=/bodegas/**, /inventarios/**, /movimientos/**

spring.cloud.gateway.server.webflux.routes[3].id=carrito
spring.cloud.gateway.server.webflux.routes[3].uri=lb://carrito-service
spring.cloud.gateway.server.webflux.routes[3].predicates[0]=Path=/carrito/**, /items/**

spring.cloud.gateway.server.webflux.routes[4].id=ordenes
spring.cloud.gateway.server.webflux.routes[4].uri=lb://ordenes-service
spring.cloud.gateway.server.webflux.routes[4].predicates[0]=Path=/ordenes/**, /historial/**, /estado/**, /detalles/**

spring.cloud.gateway.server.webflux.routes[5].id=pagos
spring.cloud.gateway.server.webflux.routes[5].uri=lb://pagos-service
spring.cloud.gateway.server.webflux.routes[5].predicates[0]=Path=/pagos/**, /transacciones/**, /estados/**, /reembolsos/**

spring.cloud.gateway.server.webflux.routes[6].id=logistica
spring.cloud.gateway.server.webflux.routes[6].uri=lb://logistica-service
spring.cloud.gateway.server.webflux.routes[6].predicates[0]=Path=/comunas/**, /direcciones/**, /envios/**, /regiones/**

spring.cloud.gateway.server.webflux.routes[7].id=resenas
spring.cloud.gateway.server.webflux.routes[7].uri=lb://resenas-service
spring.cloud.gateway.server.webflux.routes[7].predicates[0]=Path=/reacciones/**, /resenas/**