spring:
  application:
    name: config-server
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations: file:../app-config
          add-label-locations: false
server:
  port: 8888
